# -------------------------
# PORT 80 (HTTP)
# -------------------------
<VirtualHost *:80>
    ServerName stats.streamsnip.com

    # Redirect everything to HTTPS (non-www)
    Redirect permanent / https://stats.streamsnip.com/
</VirtualHost>


# -------------------------
# PORT 443 (HTTPS)
# -------------------------
<VirtualHost *:443>
    ServerName stats.streamsnip.com
    AllowEncodedSlashes On

    WSGIScriptAlias / /var/www/yt_stats_api/app.wsgi
    Protocols h2 http/1.1

    <Directory /var/www/yt_stats_api/>
        Require all granted
    </Directory>

    <Location "/server-status">
        SetHandler server-status
    </Location>

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/stats.streamsnip.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/stats.streamsnip.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/stats.streamsnip.com/chain.pem

    ErrorLog ${APACHE_LOG_DIR}/error.log
    LogLevel error
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>